Sprint 2/step 2
gold22/react-burger pull request #4
Opened 2021-12-08 12:37 UTC by gold22

2021-12-08 19:50 UTC, grishbar requested changes
Отлично, проделана большая, качестванная работа, круто что подключил линтер. В целом абсолютно корректно воспользовался redux, добавил усилители для запросов в сеть и всегда возвращаешь дефолтное состояние. Весь функицонал проекта работает верно, согласно тз.
Поправь пожалуйста состояние которое возвращаешь при ошибках в запросе, и приму работу. Также будет хорошо если поправишь все пункты, "можно лучше"

2021-12-08 19:50 UTC, grishbar commented on src/components/app/app.jsx
> +    );
`можно лучше`
```
    React.useEffect(
        dispatch(getIngredients()),
        [dispatch],
    );
```

2021-12-08 19:50 UTC, grishbar commented on src/components/app/app.jsx
> +            }
`можно лучше`
если хочешь найти элемент в массиве, то всегда поьлзуйся методом [find](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/find), такой код намного проще читается и семантически более верен

2021-12-08 19:50 UTC, grishbar commented on src/components/app/app.jsx
> +            <main />
`можно лучше`
хотелось бы конечно лоадер видеть во время загрузки

2021-12-08 19:50 UTC, grishbar commented on src/components/app/app.jsx
> +            )}
`можно лучше`
не очень понятно, что такое IngredientDetails,  лучше будет если ты в названии добавишь ему слово Modal

2021-12-08 19:50 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
> +    ));
`отлично`
отличное красивое решение, для подсчета суммы ингредиентов

2021-12-08 19:50 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    };
`можно лучше`
твое решение тоже ок, но оно очень тяжело читается и масштабируется, попробуй воспользоваться хуком useInView из библиотеки -  ['react-intersection-observer'](https://www.npmjs.com/package/react-intersection-observer)

2021-12-08 19:50 UTC, grishbar commented on src/components/constructor-element/constructor-element.jsx
> +            }
`можно лучше` очень тяжелую вложенную логику написал, такое прочитать стороннему разработчику займет уйму времени, старайся избегать вложенных if else так как это сильно нагружает читабельность кода, примерно вот так можешь написать, написал на вскидку, так, что проверь, что функционал не сломался:
```
            const isItemReordering = 'index' in item;
            if (isItemReordering) {
                dispatch(moveIngredient(item.index, index));
                return;
            }
            if (item.ingredient.type === 'bun') {
                dispatch(setBun(item.ingredient));
                return;
            }
            dispatch(addIngredient(item.ingredient, index));
```

2021-12-08 19:50 UTC, grishbar commented on src/components/constructor-element/constructor-element.jsx
> +            } else if (item.ingredient.type === 'bun') {
`можно лучше`
также  в коде у тебя не должно быть "магических переменных",  так как ты в контексте, то для тебя очевидно, что такое 'bun' , но для стороннего человека, это будет непонятно, магические такие переменные принято выносить из компонента в SNAKE_CASE и давать им осмысленное название
```
BUN_TYPE = 'bun';
```

2021-12-08 19:50 UTC, grishbar commented on src/components/constructor-element/constructor-element.jsx
> +    };
`можно лучше`
так то ты правильно назвал, свой хэндлер аналогично пропсе которую принимает компонент, но все таки она отвечает за совсем другое, так, что на мой взгляд будет корректным назвать ее -
`handleRemoveIngredient`

2021-12-08 19:50 UTC, grishbar commented on src/components/constructor-elements/constructor-elements.jsx
> +                    key="top"
`можно лучше`
кажется эта пропса тут лишняя

2021-12-08 19:50 UTC, grishbar commented on src/components/constructor-elements/constructor-elements.jsx
> +                        index={index}
`можно лучше`
индексация по индексу [не круто](https://robinpokorny.medium.com/index-as-a-key-is-an-anti-pattern-e0349aece318), можно воспользоваться [uuid](https://www.npmjs.com/package/uuid)

2021-12-08 19:50 UTC, grishbar commented on src/services/api-client.js
>          }
почему catch никак не обрабатывается?

2021-12-08 19:50 UTC, grishbar commented on src/services/api-client.js
>      async getIngredients() {
`можно лучше`
кажется в этой функции очень много лишних ifов и обрати внимание, что у тебя есть недостижимые if избавься от лишнего кода в этой функции

2021-12-08 19:50 UTC, grishbar commented on src/services/reducers/constructor.js
> +import * as actions from '../actions/constructor';
`можно лучше`
заимпортируй экшены вот так:
```
import {
  SET_BUN,
  ADD_INGREDIENT,
  REMOVE_INGREDIENT,
} from '../actions/constructor-ingredients';
```
так будет намного красивей код и не придется постоянно дублировать actions

2021-12-08 19:50 UTC, grishbar commented on src/services/reducers/constructor.js
> +        const { ingredients } = state;
`можно лучше`
довольно спорный вопрос, но на мой взгляд, если тебе не нужно изменять стейт, то отправляй action условно в компоненте, а не реализуй эту логику здесь, а то ты экшен вызвал, но стейт никак не изменился, выглядит странновато

2021-12-08 19:50 UTC, grishbar commented on src/services/reducers/constructor.js
> +            ],
`можно лучше`
тут можно напорядок проще логику написать, подумай как

2021-12-08 19:50 UTC, grishbar commented on src/services/reducers/ingredients-list.js
> +        };
`надо исправить`
при ошибке в запросе ты должен возвращать дефолтный стейт и loadError: action.message,
не надо хранить потенциально невалидные данные в стейте

2021-12-09 05:58 UTC, gold22 commented on src/components/app/app.jsx
> +    );
ругается eslint если так сделать
`ESLint: React Hook useEffect received a function whose dependencies are unknown. Pass an inline function instead.(react-hooks/exhaustive-deps)`

2021-12-09 06:26 UTC, gold22 commented on src/components/app/app.jsx
> +            )}
Это имя определено в задании.

2021-12-09 06:36 UTC, gold22 commented on src/services/api-client.js
>      async getIngredients() {
из-за отсутствия спецификации работы api приходится обрабатывать все возможные варианты и сложно понять какие из if-фов недостижимы

2021-12-09 10:43 UTC, gold22 commented on src/services/reducers/constructor.js
> +            ],
чтобы меньше кода было что-то не получается

2021-12-10 03:19 UTC, grishbar commented on src/services/api-client.js
>      async getIngredients() {
очевидно, что последние три if недостижимы, посмотри внимательней на них, также я не очень понял почему ты пытаешься обратиться к result.success, JSON.parse возвращает объект который получился из json и там свойства success никогда не будет, поправь меня если я чего то не так понял в твоем коде. 
Твоя функция должна быть примерно такая, при таком написании ты отловишь все ошибки, если хочешь тут не составит сложности дописать вывод красивых ошибок (написал не проверив, так, что не забудь проверить если будешь менять), такая функция сделает ровно тоже самое, что и твоя но написана куда более лаконично, но тем не менее это все еще не продакшн решение в идеале твоя функция запроса к данным возвращает объект, с результатом и ошибкой, и если там есть ошибка, то ты ее корректно внутри redux обрабатываешь (вызываешь action для ошибки при запросе)
```
    static fetch(url, options = {}) {
        return fetch(url, options)
            .then((response) => {
                if (!response.ok) {
                    throw new Error(`Ошибка HTTP запроса ${response.status}`);
                }
                return response.text();
            })
            .then((res) => JSON.parse(res))
            .catch((error) => {
                throw new Error(`Произошла неожиданная ошибка при обработке запроса - ${error}`);
            });
    }
```

2021-12-10 03:24 UTC, grishbar approved these changes
работу принимаю, но поправь пожалуйста, то, как ты делаешь запрос на бэкенд в классе ApiClient

2021-12-11 13:33 UTC, gold22 commented on src/services/api-client.js
>      async getIngredients() {
Если например отправить запрос на создание заказа с пустым списком ингредиентов, то API возвращает HTTP код 400 и JSON объект
```json
{"success":false,"message":"Ingredient ids must be provided"}
```
Соответственно вот это будет не очень хорошо работать
```js
if (!response.ok) {
	throw new Error(`Ошибка HTTP запроса ${response.status}`);
}
```
поскольку вместо реальной ошибки "Ingredient ids must be provided" мы покажем пользователю "Ошибка HTTP запроса 400".

В спике ингредиентов также возвращается поле success
```js
{"success":true,"data":[{"_id":"60d3b41abdacab0026a733c6","name":"Краторная булка N-200i","type":...
```
Соответственно result.success нужно в первую очередь проверять.

Вариант
```
.then((res) => JSON.parse(res))
.catch((error) => {
throw new Error(`Произошла неожиданная ошибка при обработке запроса - ${error}`);
});
```
тоже не очень хороший, потому что когда нам не пришел валидный JSON то это скорее всего ответил web или reverse proxy сервер и там обычный текст типа "503 Service Unavailable", и
мы вместо реальной ошибки пользователю покажем например "Unexpected token S in JSON at position 4".

Поэтому я не обрабатываю ошибку тут
```
try {
	result = JSON.parse(resultText);
} catch (error) {
}
```
и предпочитаю показать пользователю то что пришло как есть.

Можно упростить обработку ответа сервера если предположить что API всегда возвращает JSON документ с полем success и полем message в случае ошибки.
Поправлю код в соответствии с этим предположением.

2021-12-11 14:04 UTC, gold22 commented on src/services/api-client.js
>          }
ответил ниже

2021-12-11 14:15 UTC, gold22 commented
ApiClient поправил, по нему написал комментарий выше

2021-12-13 01:02 UTC, grishbar commented on src/services/api-client.js
>      async getIngredients() {
ты выкидываешь ошибку и в блоке catch отлавливаешь объект ошибки и там обрабатываешь, и выводишь сообщение, которое хочешь

2021-12-13 01:03 UTC, grishbar commented
Работу принимаю, удачи в дальнейшем обучении

2021-12-13 05:52 UTC, merged